site_name:           KirchMig.jl
repo_url:            https://github.com/cako/KirchMig.jl
site_description:    Simple-to-use Kirchhoff migration toolset
site_author:         Carlos Alberto da Costa Filho
theme:
  name: material #windmill #readthedocs #cluster #cinder #
  palette:
    primary: 'teal'
    accent: 'pink'
  logo: 'images/logo.svg'
google_analytics: ['UA-107214355-3', 'cako.github.io/KirchMig.jl']

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Examples: examples.md

- Documentation:
    - Function Index: function/index.md
    - function/map.md
    - function/eikonal.md
    - function/optimization.md
    - function/regularization.md

- About:
  - License: LICENSE.md

